export const defaultTheme = {
  colors: {
    primary: '#E44449',
    secondary: '#F15156',
    select: '#F75F64',
    yellow: '#F4D35E',
    blue: '#0D3B66',
    bg: '#FDECED',
    rose: '#FBE1E2',
    white: '#FFFFFF',
    lightBrown: '#CFB5BB',
  },
  font: {
    family: '"Nunito", sans-serif',
    light: 200,
    normal: 400,
    semiBold: 600,
    bold: 700,
    extraBold: 800,
    sizes: {
      huge: '7.2rem',
      xlarge: '2.4rem',
      large: '2rem',
      medium: '1.6rem',
      small: '1.2rem',
    },
    lineHeight: '120%',
  },
  borderRadius: '1.5rem',
  spacings: {
    small: '1.2rem',
    medium: '2rem',
    huge: '12rem',
  },
} as const
